// This file is @generated by prost-build.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Agent {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// projid
    #[prost(string, tag = "2")]
    pub target: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub intranet: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub username: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub hostname: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub platform: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub arch: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub process: ::prost::alloc::string::String,
    #[prost(string, tag = "9")]
    pub pid: ::prost::alloc::string::String,
}
/// 配置
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Config {
    /// 0-default 1-init  2-exit
    #[prost(int32, tag = "1")]
    pub action: i32,
    /// npcid
    #[prost(string, tag = "2")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub addr: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub ctype: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub enckey: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub enctype: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub proxy: ::prost::alloc::string::String,
}
