// This file is @generated by prost-build.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(poem_openapi::Object)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Agent {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// projid
    #[prost(string, tag = "2")]
    pub target: ::prost::alloc::string::String,
    /// 内网地址
    #[prost(string, tag = "3")]
    pub intranet: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub username: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub hostname: ::prost::alloc::string::String,
    /// windows / unix / drwin
    #[prost(string, tag = "6")]
    pub platform: ::prost::alloc::string::String,
    /// x32 / x64
    #[prost(string, tag = "7")]
    pub arch: ::prost::alloc::string::String,
    /// 进程路径
    #[prost(string, tag = "8")]
    pub process: ::prost::alloc::string::String,
    /// 进程pid
    #[prost(string, tag = "9")]
    pub pid: ::prost::alloc::string::String,
    #[prost(string, tag = "20")]
    pub internet: ::prost::alloc::string::String,
    /// 备注
    #[prost(string, tag = "21")]
    pub note: ::prost::alloc::string::String,
    #[prost(sint64, tag = "22")]
    pub updateat: i64,
    #[prost(bool, tag = "23")]
    pub npc2: bool,
}
/// 配置更新
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Config {
    /// npcid
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// 0-default 1-init  2-exit
    #[prost(int32, tag = "2")]
    pub action: i32,
    /// 交互地址
    #[prost(string, tag = "3")]
    pub callback1: ::prost::alloc::string::String,
    /// 其它配置
    #[prost(string, tag = "4")]
    pub config: ::prost::alloc::string::String,
    /// 加密key
    #[prost(string, tag = "5")]
    pub enckey: ::prost::alloc::string::String,
    ///
    #[prost(int32, tag = "6")]
    pub sleep: i32,
    ///
    #[prost(string, tag = "7")]
    pub headers: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub proxy: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Entry {
    #[prost(string, tag = "1")]
    pub url: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub path: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub size: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub auth: ::prost::alloc::string::String,
    #[prost(bool, tag = "5")]
    pub isfile: bool,
    #[prost(sint64, tag = "6")]
    pub modified: i64,
}
/// 基础命令
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Action {
    #[prost(string, tag = "1")]
    pub act: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub path: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub args: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "5")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, repeated, tag = "6")]
    pub entrys: ::prost::alloc::vec::Vec<Entry>,
}
/// 插件
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Plugin {
    #[prost(bytes = "vec", tag = "1")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    /// ld-加载插件/请求插件、  ss-加载成功   ex-执行插件 dd-插件回显
    #[prost(string, tag = "2")]
    pub act: ::prost::alloc::string::String,
    /// exe-  dll-
    #[prost(string, tag = "3")]
    pub arch: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub args: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub entry: ::prost::alloc::string::String,
}
/// npc 列表更新
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AgentList {
    #[prost(string, tag = "1")]
    pub status: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub agents: ::prost::alloc::vec::Vec<Agent>,
}
/// 日志
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Logs {
    #[prost(string, tag = "1")]
    pub r#type: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub time: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub data: ::prost::alloc::string::String,
}
/// 所有事件都走这个类型
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AgentEvent {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub sendto: ::prost::alloc::string::String,
    #[prost(oneof = "agent_event::Enumof", tags = "10, 11, 12, 13, 20, 21")]
    pub enumof: ::core::option::Option<agent_event::Enumof>,
}
/// Nested message and enum types in `AgentEvent`.
pub mod agent_event {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Enumof {
        #[prost(message, tag = "10")]
        Init(super::Agent),
        #[prost(message, tag = "11")]
        Conf(super::Config),
        #[prost(message, tag = "12")]
        Action(super::Action),
        #[prost(message, tag = "13")]
        Plugin(super::Plugin),
        #[prost(message, tag = "20")]
        Logs(super::Logs),
        #[prost(message, tag = "21")]
        List(super::AgentList),
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WsResize {
    #[prost(sint64, tag = "1")]
    pub cols: i64,
    #[prost(sint64, tag = "2")]
    pub rows: i64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WsData {
    #[prost(string, tag = "1")]
    pub data: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WsPing {}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WsMsg {
    #[prost(oneof = "ws_msg::Enumof", tags = "1, 2, 3")]
    pub enumof: ::core::option::Option<ws_msg::Enumof>,
}
/// Nested message and enum types in `WsMsg`.
pub mod ws_msg {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Enumof {
        #[prost(message, tag = "1")]
        Data(super::WsData),
        #[prost(message, tag = "2")]
        Resize(super::WsResize),
        #[prost(message, tag = "3")]
        Ping(super::WsPing),
    }
}
